name: League
version: 0.0.1
description: This plugin
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.league.League
database: false

commands:
  leave:
    description: set your displayname
  league:
    description: set your display name