name: Team
version: 0.0.1
description: This plugin allows players to create teams
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.teams.Teams
database: false