name: Sprint
version: 0.0.1
description: This plugin bans players who use sprint hack
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.sprint.Plugin
database: false

permisions:
  rabrg.sprint.bypass:
    description: Allows you to bypass the sprint hack