name: Bedrock
version: 0.0.1
description: This plugin disabled placing saplings at bedrock levels
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.bedrock.Plugin
database: false