name: Ares
version: 0.0.1
description: This plugin allows players to pick kits
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.ares.Plugin
database: false

permisions:
  rabrg.ares.sign.create:
    description: Allows you to create Ares signs
  rabrg.ares.sign.use:
    description: Allows you to use Ares signs