name: Border
version: 0.0.1
description: This plugin kicks and teleports players who pass the border to spawn
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.border.Plugin
database: false
