name: Cooldowns
version: 0.0.1
description: This plugin provides command cooldowns
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.cooldowns.Plugin
database: false