name: MobSpawner
version: 0.0.1
description: This plugin allows players that can mine spawners to explode spawners with TNT
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.mobspawner.Plugin
database: false
