name: RabrgHome
main: me.rabrg.home.RabrgHomePlugin
version: 0.0.1
author: Rabrg
database: true
description: This plugin allows players to set multiple homes.
depend: [Essentials]
commands:
  sethome:
    aliases: [addhome]
    description: Sets your current position to a home of the given name
    usage: |
           /<command> <name> [player]
           Example: /<command> BeachHouse
  listhomes:
    aliases: [homes]
    description: Lists all homes that you own
    usage: /<command> [player]
  gohome:
    aliases: [home]
    description: Goes to a home
    usage: /<command> <name> [player]
  deletehome:
    aliases: [delhome, removehome]
    description: Deletes a home
    usage: /<command> <name>