name: Leaderboard
version: 0.0.1
description: This plugin creates a leaderboard
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.leaderboard.Plugin
database: false

commands:
  kills:
    description: Get the kill count of a player
  deaths:
    description: Get the death count of a player