name: WaterTNT
version: 0.0.1
description: This plugin mutes TNT's damage if it explodes in water
load: STARTUP
author: Rabrg
authors: [Ryan Greene]
website: http://forums.bukkit.org/members/rabrg.90565009/
main: me.rabrg.watertnt.Plugin
database: false
